Add validation for when still birth but not N/A
flourishbhp/flourish-form-validations pull request #224
Opened 2024-12-03 09:25 UTC by kmneya

2024-12-09 09:55 UTC, amediphoko requested changes

2024-12-09 09:55 UTC, amediphoko commented on flourish_form_validations/form_validators/maternal_delivery_form_validation.py
>          if feeding_mode == NOT_APPLICABLE and (still_births == 0):
there's an `applicable_if` on condition validation func on the EDC validators that you can use.

2024-12-10 06:49 UTC, kmneya commented on flourish_form_validations/form_validators/maternal_delivery_form_validation.py
>          if feeding_mode == NOT_APPLICABLE and (still_births == 0):
Noted

2024-12-11 09:33 UTC, amediphoko approved these changes

2024-12-11 09:33 UTC, merged